d /var/lib/jacques         0750 jacques jacques -
d /var/lib/jacques/library 0750 jacques jacques -
d /var/lib/jacques/tmp     0750 jacques jacques -
d /etc/jacques             0750 root    root    -
